import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const payload = path.join(root, 'production-overlays/cockpit-r141-arrears-evidence-v1-20260828-v1/payload')
const runtime = fs.readFileSync(path.join(payload, 'aph2-r141-arrears-evidence-v1.js'), 'utf8')
const styles = fs.readFileSync(path.join(payload, 'aph2-r141-arrears-evidence-v1.css'), 'utf8')
const index = fs.readFileSync(path.join(payload, 'index.html'), 'utf8')
const analysis = fs.readFileSync(path.join(root, 'server/src/arrears-analysis.ts'), 'utf8')
const route = fs.readFileSync(path.join(root, 'server/src/routes/arrears-analysis.ts'), 'utf8')
const connectors = fs.readFileSync(path.join(root, 'server/src/arrears-connectors.ts'), 'utf8')
const connectorStore = fs.readFileSync(path.join(root, 'server/src/arrears-connector-store.ts'), 'utf8')
const householdActions = fs.readFileSync(path.join(root, 'server/src/arrears-household-actions.ts'), 'utf8')
const wecomLedgerConnector = fs.readFileSync(path.join(root, 'server/src/wecom-ledger-connector.ts'), 'utf8')
const qxmEvidenceConnector = fs.readFileSync(path.join(root, 'server/src/qxm-evidence-connector.ts'), 'utf8')
const qxmEvidenceTransport = fs.readFileSync(path.join(root, 'server/src/qxm-evidence-process-transport.ts'), 'utf8')
const qxmEvidenceJob = fs.readFileSync(path.join(root, 'server/src/qxm-evidence-job.ts'), 'utf8')
const qxmEvidenceCli = fs.readFileSync(path.join(root, 'server/src/qxm-evidence-sync-cli.ts'), 'utf8')
const wecomLedgerTransport = fs.readFileSync(path.join(root, 'server/src/wecom-ledger-process-transport.ts'), 'utf8')
const wecomLedgerJob = fs.readFileSync(path.join(root, 'server/src/wecom-ledger-job.ts'), 'utf8')
const wecomLedgerCli = fs.readFileSync(path.join(root, 'server/src/wecom-ledger-sync-cli.ts'), 'utf8')
const wecomLedgerExtractor = fs.readFileSync(path.join(root, 'server/scripts/wecom-ledger-extractor.py'), 'utf8')
const qxmEvidenceExtractor = fs.readFileSync(path.join(root, 'server/scripts/qxm-evidence-extractor.py'), 'utf8')
const database = fs.readFileSync(path.join(root, 'server/src/db.ts'), 'utf8')
const lvzaiAdapter = fs.readFileSync(path.join(root, 'server/src/lvzai-arrears-adapter.ts'), 'utf8')
const lvzaiTransport = fs.readFileSync(path.join(root, 'server/src/lvzai-http-transport.ts'), 'utf8')
const lvzaiJob = fs.readFileSync(path.join(root, 'server/src/lvzai-arrears-job.ts'), 'utf8')
const lvzaiJobScript = fs.readFileSync(path.join(root, 'server/src/lvzai-sync-cli.ts'), 'utf8')
const lvzaiLoginScript = fs.readFileSync(path.join(root, 'server/scripts/lvzai-login.py'), 'utf8')
const scopeDiscovery = fs.readFileSync(path.join(root, 'server/src/lvzai-scope-discovery.ts'), 'utf8')
const scopeDiscoveryScript = fs.readFileSync(path.join(root, 'server/src/lvzai-discover-cli.ts'), 'utf8')
const productionBuilder = fs.readFileSync(path.join(root, 'scripts/build-production-release.mjs'), 'utf8')
const serverPackage = JSON.parse(fs.readFileSync(path.join(root, 'server/package.json'), 'utf8'))

test('R141 links full green-house codes to project-scoped QXM short room codes', () => {
  assert.match(analysis, /function normalizedHouseParts/)
  assert.match(analysis, /function shortHouseKey/)
  assert.match(analysis, /buildLedgerResourceResolver/)
  assert.match(analysis, /resolver\.ambiguous\.has/)
  assert.match(route, /buildLedgerResourceResolver\(ledgerParsed\.rows\)/)
  assert.match(route, /shortRoomMatchedCommunicationRows/)
  assert.match(route, /batches\/:id\/match-quality/)
  assert.match(route, /NOT EXISTS \(\s*SELECT 1 FROM arrears_ledger_rows/)
  assert.match(route, /房屋号未匹配到当前项目内唯一台账资源/)
})

test('R141 defines a replaceable, fail-closed LvZai household arrears connector', () => {
  assert.match(connectors, /interface ArrearsSourceConnector/)
  assert.match(connectors, /normalizeLvzaiArrearsEnvelope/)
  assert.match(connectors, /ARREARS_CONNECTOR_QUALITY_BLOCKED/)
  assert.match(connectors, /五段式roomSign/)
  assert.match(connectors, /declaredTotalAmount/)
  assert.match(connectorStore, /publishLvzaiArrears/)
  assert.match(connectorStore, /status='superseded'/)
  assert.match(connectorStore, /拒绝重新发布已被更新批次替代/)
  assert.match(database, /CREATE TABLE IF NOT EXISTS arrears_source_sync_runs/)
  assert.match(database, /CREATE TABLE IF NOT EXISTS arrears_lvzai_facts/)
  assert.match(database, /CREATE TABLE IF NOT EXISTS arrears_wecom_ledger_facts/)
  assert.match(database, /CREATE TABLE IF NOT EXISTS arrears_evidence_conflict_reviews/)
  assert.match(database, /CREATE TABLE IF NOT EXISTS arrears_qxm_evidence/)
  assert.match(route, /arrears\/connectors\/status/)
  assert.match(connectorStore, /publishWecomLedger/)
  assert.match(connectorStore, /readArrearsEvidenceConflicts/)
  assert.match(connectorStore, /reviewArrearsEvidenceConflict/)
  assert.match(connectorStore, /publishQxmEvidence/)
  assert.match(connectorStore, /lvzai_without_qxm_evidence/)
  assert.match(connectorStore, /qxm_room_review_required/)
  assert.match(householdActions, /knownFacts/)
  assert.match(householdActions, /reasonableJudgments/)
  assert.match(householdActions, /pendingVerification/)
  assert.match(householdActions, /reported_paid_pending_lvzai/)
  assert.match(householdActions, /不得改写缴费状态/)
  assert.match(route, /\/api\/arrears\/connectors\/household-actions/)
  assert.match(route, /无权查看该服务中心逐户建议/)
  assert.match(connectorStore, /expectedVersion/)
  assert.match(connectorStore, /reported_paid_but_lvzai_arrears/)
  assert.match(route, /connectors\/evidence-conflicts/)
  assert.match(route, /serviceCenterValues\(req\.user\)/)
  assert.match(route, /无权查看该服务中心冲突队列/)
  assert.match(route, /offset: \(page - 1\) \* limit/)
  assert.match(route, /evidence-conflicts\/:conflictKey\/review/)
  assert.match(route, /不接收自由备注/)
  assert.match(route, /review_arrears_evidence_conflict/)
  assert.match(route, /status\(409\)/)
  assert.match(route, /readArrearsConnectorStatus\(db, 'wecom_ledger'\)/)
  assert.match(lvzaiAdapter, /LVZAI_ARREARAGE_ENDPOINT = '\/oas\/getArrearage'/)
  assert.match(lvzaiAdapter, /lvzaiArrearageRequest/)
  assert.match(lvzaiAdapter, /type: 1/)
  assert.match(lvzaiAdapter, /abortDate: businessDate/)
  assert.match(lvzaiAdapter, /合计与费项逐行重算不一致/)
  assert.match(lvzaiAdapter, /超出授权项目前缀/)
  assert.match(lvzaiAdapter, /LvzaiSessionExpiredError/)
  assert.match(lvzaiTransport, /会话状态文件权限必须为600/)
  assert.match(lvzaiTransport, /qdp-polestar-web\$\{endpoint\}/)
  assert.match(lvzaiTransport, /fs\.chmodSync\(this\.statePath, 0o600\)/)
  assert.match(lvzaiTransport, /响应超过16MiB安全上限/)
  assert.match(lvzaiJob, /runLvzaiArrearsJob/)
  assert.match(lvzaiJob, /mode: 'dry-run'/)
  assert.match(lvzaiJob, /正式发布缺少生产环境与业务日期双重确认/)
  assert.match(lvzaiJob, /不得包含凭据字段/)
  assert.ok(lvzaiJobScript.indexOf('publicationConfirmed') < lvzaiJobScript.indexOf("import('./db.js')"))
  assert.equal(serverPackage.scripts['sync-lvzai-arrears'], 'tsx scripts/sync-lvzai-arrears.ts')
  assert.match(scopeDiscovery, /discoverLvzaiArrearsScope/)
  assert.match(scopeDiscovery, /state: 'empty' \| 'conflict' \| 'invalid_response'/)
  assert.match(scopeDiscovery, /config: passed \?/)
  assert.match(scopeDiscoveryScript, /LVZAI_ARREARS_SCOPE_WRITE_CONFIRM/)
  assert.match(scopeDiscoveryScript, /result\.state !== 'passed'/)
  assert.doesNotMatch(scopeDiscoveryScript, /result\.config[^\n]*process\.stdout/)
  assert.equal(serverPackage.scripts['discover-lvzai-arrears-scope'], 'tsx scripts/discover-lvzai-arrears-scope.ts')
  assert.match(lvzaiLoginScript, /os\.environ\.get\("LVZAI_USER"/)
  assert.match(lvzaiLoginScript, /os\.environ\.get\("LVZAI_PWD"/)
  assert.match(lvzaiLoginScript, /os\.replace\(temporary, STATE\)/)
  assert.match(lvzaiLoginScript, /os\.chmod\(STATE, 0o600\)/)
  assert.doesNotMatch(lvzaiLoginScript, /USER\s*=\s*["'][^"']+["']/)
  assert.doesNotMatch(lvzaiLoginScript, /erp_api_capture|home_text|captured\s*=|page\.screenshot/)
  assert.doesNotMatch(lvzaiLoginScript, /验证码识别|print\(.*code/)
  assert.match(productionBuilder, /backend\/operations\/lvzai-login\.py/)
  assert.match(productionBuilder, /lvzai-sync-cli\.js/)
  assert.match(productionBuilder, /lvzai-discover-cli\.js/)
  assert.match(productionBuilder, /lvzaiLoginScript,/)
  assert.match(wecomLedgerConnector, /WecomControlledLedgerConnector/)
  assert.match(wecomLedgerConnector, /normalizeWecomLedgerEnvelope/)
  assert.match(wecomLedgerConnector, /reported_paid_pending_lvzai/)
  assert.match(wecomLedgerConnector, /authoritativeAmountFields: 0/)
  assert.match(wecomLedgerConnector, /缺少完整五段式房屋号/)
  assert.match(wecomLedgerConnector, /房屋号超出工作表授权前缀/)
  assert.match(wecomLedgerConnector, /缺少稳定证据ID/)
  assert.doesNotMatch(wecomLedgerConnector, /customerName|phoneMasked|欠费金额:/)
  assert.match(qxmEvidenceConnector, /QxmIncrementalEvidenceConnector/)
  assert.match(qxmEvidenceConnector, /normalizeQxmEvidenceEnvelope/)
  assert.match(qxmEvidenceConnector, /增量游标未推进或发生循环/)
  assert.match(qxmEvidenceConnector, /matchState: house \? 'matched' : 'review_required'/)
  assert.match(qxmEvidenceConnector, /contentHmac/)
  assert.match(qxmEvidenceTransport, /shell: false/)
  assert.match(qxmEvidenceTransport, /QXM_READ_TOKEN/)
  assert.match(qxmEvidenceTransport, /QXM_SESSION_FILE/)
  assert.match(qxmEvidenceTransport, /QxmEvidenceSessionExpiredError/)
  assert.match(qxmEvidenceJob, /权限必须为600/)
  assert.match(qxmEvidenceJob, /cursorAdvanced, publication/)
  assert.match(qxmEvidenceJob, /publicationConfirmed/)
  assert.match(qxmEvidenceCli, /--initialize-cursors/)
  assert.match(qxmEvidenceCli, /ARREARS_QXM_PUBLISH_CONFIRM/)
  assert.doesNotMatch(qxmEvidenceConnector, /contentMasked|customerName|phoneMasked/)
  assert.match(wecomLedgerExtractor, /https:\/\/doc\.weixin\.qq\.com/)
  assert.match(wecomLedgerExtractor, /tab-bar-item\[data-tab-id/)
  assert.match(wecomLedgerExtractor, /\/dop-api\/get\/sheet/)
  assert.match(wecomLedgerExtractor, /ALLOWED_SHEET_QUERY_KEYS/)
  assert.match(wecomLedgerExtractor, /initialAttributedText/)
  assert.match(wecomLedgerExtractor, /related_sheet/)
  assert.match(wecomLedgerExtractor, /webpackRequire\(222272\)/)
  assert.match(wecomLedgerExtractor, /setRange\?\.cellAtPositions/)
  assert.doesNotMatch(wecomLedgerExtractor, /navigator\.clipboard|ClipboardTableParser/)
  assert.match(wecomLedgerExtractor, /FULL_ROOM\.fullmatch/)
  assert.doesNotMatch(wecomLedgerExtractor, /合计.*rows\.append|实施责任人.*rows\.append/)
  assert.match(qxmEvidenceExtractor, /\/admin\/work_party\/getExternalContact/)
  assert.match(qxmEvidenceExtractor, /\/admin\/work_msg_audit\/getExternalMsgList/)
  assert.match(qxmEvidenceExtractor, /\/admin\/work_msg_audit\/getExternalMsgContent/)
  assert.match(qxmEvidenceExtractor, /upperOccurredAt/)
  assert.match(qxmEvidenceExtractor, /has_more = total > limit/)
  assert.match(qxmEvidenceExtractor, /PlaywrightTimeoutError/)
  assert.match(qxmEvidenceExtractor, /SystemExit\(43\)/)
  assert.doesNotMatch(qxmEvidenceExtractor, /print\(.*token|screenshot|logger/)
  assert.match(wecomLedgerTransport, /shell: false/)
  assert.match(wecomLedgerTransport, /stdio: \['pipe', 'pipe', 'ignore'\]/)
  assert.match(wecomLedgerTransport, /响应超过16MiB安全上限/)
  assert.match(wecomLedgerTransport, /会话文件权限必须为600/)
  assert.match(wecomLedgerTransport, /WECOM_SHOULD_NOT_LEAK|ALLOWED_CREDENTIAL_ENVIRONMENT/)
  assert.match(wecomLedgerJob, /mode: 'dry-run'/)
  assert.match(wecomLedgerJob, /authoritativeAmountFields: 0/)
  assert.match(wecomLedgerJob, /不得包含凭据字段/)
  assert.ok(wecomLedgerCli.indexOf('publicationConfirmed') < wecomLedgerCli.indexOf("import('./db.js')"))
  assert.equal(serverPackage.scripts['sync-wecom-ledger'], 'tsx scripts/sync-wecom-ledger.ts')
  assert.match(productionBuilder, /wecom-ledger-sync-cli\.js/)
  assert.match(productionBuilder, /wecom-ledger-extractor\.py/)
  assert.match(productionBuilder, /qxm-evidence-extractor\.py/)
  assert.match(productionBuilder, /qxm-evidence-sync-cli\.js/)
})

test('R141 presents the three-source evidence contract without claiming live readiness', () => {
  for (const label of ['三源证据链', '绿仔管家', '欠费事实', '企业微信', '经营填报', '企小码', '沟通证据']) assert.ok(runtime.includes(label), label)
  assert.match(runtime, /金额、账期及缴费状态以绿仔为准/)
  assert.match(runtime, /unmatched_communication_rows/)
  assert.match(runtime, /短房号未唯一匹配时不会自动合并/)
  assert.match(runtime, /房屋号已全部匹配/)
  assert.match(runtime, /openMatchDialog/)
  assert.match(runtime, /match-quality\?limit=100/)
  assert.match(runtime, /api\/arrears\/overview/)
  assert.match(runtime, /不等同于未联系/)
  assert.match(runtime, /当前批次欠费金额/)
  assert.match(runtime, /正式以绿仔为准/)
  assert.doesNotMatch(runtime, /metric\('权威欠费金额'/)
  assert.match(runtime, /已知事实/)
  assert.match(runtime, /合理判断/)
  assert.match(runtime, /待核实事项/)
  assert.match(runtime, /欠费原因尚未完成人工确认/)
  assert.match(runtime, /evidenceReferences/)
  assert.match(runtime, /api\/arrears\/connectors\/status/)
  assert.match(runtime, /尚无正式同步批次/)
  assert.match(runtime, /证据冲突复核/)
  assert.match(runtime, /connectors\/evidence-conflicts/)
  assert.match(runtime, /expectedVersion/)
  assert.match(runtime, /不接收自由备注/)
  assert.match(runtime, /人工报告已缴，绿仔仍欠费/)
  assert.match(runtime, /企小码未关联证据（自动隔离）/)
  assert.match(runtime, /企小码沟通信号存在冲突/)
  assert.match(runtime, /逐户经营建议/)
  assert.match(runtime, /\/api\/arrears\/connectors\/household-actions/)
  assert.match(runtime, /只读规则建议，不自动执行/)
  assert.match(styles, /\.arrears-conflicts/)
  assert.match(styles, /\.arrears-review-dialog/)
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/)
  assert.doesNotMatch(runtime, /innerHTML\s*=/)
  assert.match(runtime, /已通过门禁/)
  assert.match(styles, /\.arrears-source-chain/)
  assert.match(styles, /\.arrears-match-state\.is-review/)
  assert.match(styles, /\.arrears-match-dialog::backdrop/)
  assert.match(styles, /\.arrears-overview-strip/)
  assert.match(styles, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(styles, /\.arrears-evidence-layers/)
  assert.match(styles, /\.arrears-evidence-tier\.is-fact/)
  assert.match(styles, /\.arrears-evidence-tier\.is-judgement/)
  assert.match(styles, /\.arrears-evidence-tier\.is-check/)
  assert.match(styles, /\.arrears-household-actions__list summary/)
  assert.match(styles, /\.arrears-household-actions__layers/)
  assert.match(styles, /\.arrears-household-actions__recommendations/)
  assert.match(styles, /\.arrears-household-actions__priority\.is-priority/)
  assert.match(styles, /\.arrears-source-sync\.is-published/)
  assert.match(styles, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.doesNotMatch(runtime, /三源同步已就绪/)
})

test('R141 loads as a non-React enhancement and preserves the existing application module', () => {
  assert.match(index, /aph2-r141-arrears-evidence-v1\.js\?v=r141-evidence2/)
  assert.match(index, /aph2-r141-arrears-evidence-v1\.css\?v=r141-evidence1/)
  assert.match(index, /aph2-r126-arrears-ai-workflow-20260826-v2\.js"><\/script>/)
  assert.doesNotMatch(index, /aph2-r126-arrears-ai-workflow-20260826-v2\.js\?v=r141/)
  assert.match(runtime, /new MutationObserver\(mountSourceChain\)/)
})
