import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { csvCell, spreadsheetSafeText } from '../review-system/active/frontend/src/lib/csv.js'

const homeSource = await readFile(new URL('../review-system/active/frontend/src/views/HomeView.jsx', import.meta.url), 'utf8')
const botsSource = await readFile(new URL('../review-system/active/frontend/src/views/BotsView.jsx', import.meta.url), 'utf8')
const statsSource = await readFile(new URL('../review-system/active/frontend/src/views/StatsView.jsx', import.meta.url), 'utf8')
const submitSource = await readFile(new URL('../review-system/active/frontend/src/views/SubmitView.jsx', import.meta.url), 'utf8')
const reviewSource = await readFile(new URL('../review-system/active/frontend/src/views/ReviewView.jsx', import.meta.url), 'utf8')
const detailSource = await readFile(new URL('../review-system/active/frontend/src/views/ProposalDetailView.jsx', import.meta.url), 'utf8')
const knowledgeSource = await readFile(new URL('../review-system/active/frontend/src/views/KnowledgeView.jsx', import.meta.url), 'utf8')
const rulesSource = await readFile(new URL('../review-system/active/frontend/src/views/RulesView.jsx', import.meta.url), 'utf8')
const topbarSource = await readFile(new URL('../review-system/active/frontend/src/components/Topbar.jsx', import.meta.url), 'utf8')
const sidebarSource = await readFile(new URL('../review-system/active/frontend/src/components/Sidebar.jsx', import.meta.url), 'utf8')
const settingsSource = await readFile(new URL('../review-system/active/frontend/src/views/SettingsView.jsx', import.meta.url), 'utf8')
const appSource = await readFile(new URL('../review-system/active/frontend/src/App.jsx', import.meta.url), 'utf8')
const usersSource = await readFile(new URL('../review-system/active/frontend/src/views/UsersView.jsx', import.meta.url), 'utf8')
const logsSource = await readFile(new URL('../review-system/active/frontend/src/views/LogsView.jsx', import.meta.url), 'utf8')
const backendSource = await readFile(new URL('../review-system/active/backend/server.js', import.meta.url), 'utf8')
const hermesSource = await readFile(new URL('../review-system/active/hermes/server.js', import.meta.url), 'utf8')
const apiSource = await readFile(new URL('../review-system/active/frontend/src/lib/api.js', import.meta.url), 'utf8')

test('审核首页不再用正数兜底、均分或硬编码公告伪装真实数据', () => {
  assert.doesNotMatch(homeSource, /onlineRobots:\s*8/)
  assert.doesNotMatch(homeSource, /100\s*\/\s*Math\.max\(robots\.length/)
  assert.doesNotMatch(homeSource, /市场拓展审核模型新增立项报告校验/)
  assert.doesNotMatch(homeSource, /审核机器人作业标准已完成基础配置/)
  assert.doesNotMatch(homeSource, /方案详情页支持重新发起 AI 审核/)
  assert.doesNotMatch(homeSource, /'05-28'/)
  assert.match(homeSource, /勿将空值视为真实业务数据/)
  assert.match(homeSource, /暂无真实审核趋势数据/)
  assert.match(homeSource, /暂无真实专业任务数据/)
  assert.match(homeSource, /sub="完整定义核验并启用"/)
  assert.doesNotMatch(homeSource, /机器人启用数[^\n]*真实方案均分/)
  assert.match(homeSource, /账号风险统计未加载，当前状态未知/)
  assert.match(homeSource, /sub="需补充后复核"/)
  assert.doesNotMatch(homeSource, /sub="含高风险项"/)
})

test('机器人配置状态与完整定义核验状态分开呈现', () => {
  assert.match(homeSource, /已核验专业/)
  assert.doesNotMatch(homeSource, /机器人在线数/)
  assert.match(homeSource, /const enabledRobotCount = stats\.enabledProfiles \?\? 0/)
  assert.doesNotMatch(homeSource, /stats\.enabledProfiles \?\? stats\.onlineRobots/)
  assert.match(botsSource, /profile\.onlineLabel \|\| \(profile\.status === '启用' \? '启用待核验' : '停用'\)/)
  assert.match(botsSource, /profiles\.filter\(item => item\.status === '启用' && item\.definitionVerified === true\)/)
  assert.match(homeSource, /const active = profile\.status === '启用' && profile\.definitionVerified === true/)
  assert.match(homeSource, /label: active \? \(profile\.onlineLabel \|\| '已启用且已核验'\) : profile\.status === '启用' \? '启用待核验' : '停用'/)
  assert.doesNotMatch(homeSource, /text-xs text-emerald-400">● \{r\.status\}/)
  assert.match(homeSource, /当前没有已核验启用的内部运营专业，AI 审核尚未开放/)
  assert.match(homeSource, /市场拓展 AI 审核尚未开放/)
  assert.match(botsSource, /const active = profile\.status === '启用' && profile\.definitionVerified === true/)
  assert.match(botsSource, /未核验，不参与审核/)
})

test('后端不得注入示例业务、合成任务量、固定耗时或固定趋势', () => {
  assert.doesNotMatch(backendSource, /proposals\.length\s*\+\s*index\s*\+\s*2/)
  assert.doesNotMatch(backendSource, /\[42,\s*39,\s*37,\s*41,\s*38,\s*36,\s*35,\s*40\]/)
  assert.doesNotMatch(backendSource, /\{\s*date:\s*'05-22'/)
  assert.doesNotMatch(backendSource, /华北区域内部运营品质提升方案/)
  assert.doesNotMatch(backendSource, /林昌天铂院子市场拓展投标方案/)
})

test('无评分、无调用和加载失败必须与真实零值明确区分', () => {
  assert.match(statsSource, /scoredItems/)
  assert.match(statsSource, /勿将空值视为真实业务数据/)
  assert.match(submitSource, /勿将空值视为没有提交记录/)
  assert.match(submitSource, /当前未生成可信 AI 评分，已转入人工复核/)
  assert.doesNotMatch(submitSource, /AI 审核意见已自动生成/)
  assert.match(submitSource, /未能读取上传与审核就绪状态，已安全禁用新提交/)
  assert.match(reviewSource, /暂无评分/)
  assert.match(detailSource, /暂无评分/)
  assert.doesNotMatch(submitSource, /评分 \$\{item\.avgScore \|\| 0\}/)
  assert.match(topbarSource, /setNeedReminderCount\(null\)/)
  assert.match(topbarSource, /提醒状态暂不可用/)
  assert.doesNotMatch(topbarSource, /\.catch\(\(\) => \{\s*if \(active\) setNeedReminderCount\(0\)/)
  assert.match(settingsSource, /备份快照读取失败，当前列表可能已过期/)
  assert.match(settingsSource, /最近上线确认读取失败，当前记录状态未知/)
  assert.match(appSource, /为避免使用过期权限，已暂停进入业务页面/)
  assert.doesNotMatch(appSource, /refreshSession\(\)[\s\S]*?\.catch\(\(\) => \{\}\)/)
  assert.match(usersSource, /通知文案已复制，但操作留痕未写入/)
  assert.match(sidebarSource, /api\.get\('\/health'\)/)
  assert.match(sidebarSource, /health\?\.ok === true \? 'healthy' : 'error'/)
  assert.match(sidebarSource, /serviceStatus === 'error'\s*\? '连接异常'/)
})

test('本地规则待人工复核不得冒充 AI 成功，日志缺结果不得默认成功', () => {
  assert.match(reviewSource, /待人工复核/)
  assert.match(reviewSource, /trace\.status === 'success'\) return '成功'/)
  assert.match(detailSource, /trace\.status === 'success'\) return '成功'/)
  assert.match(homeSource, /trace\.status === 'success'\) return '成功'/)
  assert.match(statsSource, /item\.status === 'success'\) return '成功'/)
  assert.match(logsSource, /trace\.status === 'success'\) return '成功'/)
  assert.match(logsSource, /\(item\.result \|\| '未记录'\) === resultFilter/)
  assert.doesNotMatch(logsSource, /\(item\.result \|\| '成功'\) === resultFilter/)
})

test('已通过只能由完整复核后签发产生，模板不得代填未经核验事实', () => {
  assert.doesNotMatch(detailSource, /updateStatus\('已通过'\)/)
  assert.doesNotMatch(reviewSource, /bulkUpdateStatus\('已通过'\)/)
  assert.doesNotMatch(reviewSource, /updateStatus\(item, '已通过'\)/)
  assert.doesNotMatch(detailSource, /AI 审核意见与公司作业标准保持一致/)
  assert.match(detailSource, /请至少填写 1 条已核验的复核依据/)
  assert.match(detailSource, /请至少填写 1 条明确的后续动作/)
})

test('新增规则和知识默认停用，启用动作明确需要正式来源核验', () => {
  assert.match(knowledgeSource, /source:\s*''/)
  assert.match(knowledgeSource, /status:\s*'停用'/)
  assert.match(knowledgeSource, /sourceVerified:\s*form\.status === '启用'/)
  assert.match(rulesSource, /status:\s*'停用'/)
  assert.match(rulesSource, /basisVerified:\s*nextStatus === '启用'/)
  assert.match(knowledgeSource, /正式来源原件/)
  assert.match(rulesSource, /已批准并完成业务口径核验/)
})

test('Hermes Profile 同步不冒充业务审批，完整定义需要显式核验', () => {
  assert.match(botsSource, /standardsVerified: form\.standardsVerified === true/)
  assert.match(botsSource, /Hermes 同步不等于业务审批/)
  assert.match(botsSource, /任一物料变更都需重新核验/)
  assert.match(botsSource, /不得作为自动通过或立项结论依据/)
  assert.doesNotMatch(botsSource, /自动生成正式立项报告/)
  assert.match(settingsSource, /label: '完整 Profile 定义核验'/)
  assert.match(settingsSource, /profile\.definitionVerified !== true/)
  assert.match(settingsSource, /Hermes 技术同步不能替代业务审批/)
  assert.match(settingsSource, /unverifiedProfileItems\.length === 0/)
})

test('新方案提交在状态未知时安全关闭，未核验时仅保存待配置草稿', () => {
  assert.match(submitSource, /submissionMode:\s*'blocked'/)
  assert.match(submitSource, /reviewReady:\s*false/)
  assert.match(submitSource, /maxUploadFiles:\s*12/)
  assert.match(submitSource, /maxFileSizeBytes:\s*20 \* 1024 \* 1024/)
  assert.match(submitSource, /maxTotalSizeBytes:\s*48 \* 1024 \* 1024/)
  assert.match(submitSource, /data\.reviewReady === true/)
  assert.match(submitSource, /data\.submissionMode === 'ai-review' \|\| data\.submissionMode === 'draft-only'/)
  assert.match(submitSource, /const submissionAllowed = draftOnly \|\| \(submissionMode === 'ai-review' && reviewReady\)/)
  assert.match(submitSource, /if \(!submissionAllowed\) return setError\(reviewReadinessMessage\)/)
  assert.match(submitSource, /const proposalTitleMaxCodePoints = 120/)
  assert.match(submitSource, /const titleCodePoints = codePointLength\(trimmedTitle\)/)
  assert.match(submitSource, /titleCodePoints > proposalTitleMaxCodePoints/)
  assert.match(submitSource, /function clampCodePoints[\s\S]*?Array\.from\(String\(value\)\)\.slice\(0, maximum\)\.join\(''\)/)
  assert.match(submitSource, /onChange=\{\(e\) => setTitle\(clampCodePoints\(e\.target\.value\)\)\}/)
  assert.doesNotMatch(submitSource, /maxLength=\{proposalTitleMaxCodePoints\}/)
  assert.match(submitSource, /disabled=\{submitting \|\| !submissionAllowed\}/)
  assert.match(submitSource, /result\.status === '待专业配置'/)
  assert.match(submitSource, /本次未调用 AI，也未生成评分、专业意见或立项结论/)
  assert.match(submitSource, /reviewResult\?\.status === '待专业配置'/)
  assert.match(submitSource, /附件总量不能超过/)
  assert.doesNotMatch(submitSource, /'\.xls'/)
})

test('待专业配置草稿只能经真实审核进入后续流程', () => {
  assert.match(backendSource, /const configurationPending = proposals\.filter\(item => item\.status === statuses\.configurationPending\)\.length/)
  assert.match(backendSource, /stats:\s*\{[\s\S]*?configurationPending,/)
  assert.match(backendSource, /待专业配置草稿必须先发起 AI 审核，不能通过通用状态接口跳过审核/)
  assert.match(backendSource, /选择中包含待专业配置草稿，必须先逐项或批量发起 AI 审核/)
  assert.match(backendSource, /待专业配置草稿尚未形成审核意见，不能登记意见书预览或导出/)
  assert.match(backendSource, /待专业配置草稿尚未完成审核，不能提交人工复核结论/)
  assert.match(backendSource, /待专业配置草稿尚未完成审核，不能签发/)
  assert.match(backendSource, /待专业配置草稿尚未完成审核，不能归档/)
  assert.match(backendSource, /item\.status !== statuses\.review \|\| !item\.summary \|\| !trace/)
})

test('审核队列与详情页对待专业配置草稿实行同一业务边界', () => {
  assert.match(reviewSource, /const statusTabs = \['全部', '待专业配置'/)
  assert.match(reviewSource, /待专业配置: 'text-orange-300 bg-orange-500\/10 border-orange-400\/30'/)
  assert.match(homeSource, /待专业配置: 'text-orange-300 bg-orange-500\/10 border-orange-400\/30'/)
  assert.match(reviewSource, /selectedConfigurationPendingCount/)
  assert.match(reviewSource, /所选方案包含待专业配置草稿，请先发起 AI 审核/)
  assert.match(reviewSource, /所选草稿尚未生成审核意见，不能导出意见书/)
  assert.match(reviewSource, /单次最多选择 2 个方案/)
  assert.match(reviewSource, /待 AI 审核/)
  assert.match(reviewSource, /isConfigurationPending\(item\) \? '未开放'/)
  assert.match(reviewSource, /!isConfigurationPending\(item\) && item\.signOffStatus === '待签发'/)
  assert.match(reviewSource, /!isConfigurationPending\(item\) && item\.archiveStatus === '待归档'/)
  assert.match(reviewSource, /isConfigurationPending\(item\) \? '待 AI 审核' : \(item\.manualReviewStatus/)
  assert.match(reviewSource, /isConfigurationPending\(item\) \? '未开放' : \(item\.signOffStatus/)
  assert.match(reviewSource, /isConfigurationPending\(item\) \? '未开放' : \(item\.archiveStatus/)

  assert.match(detailSource, /api\.get\('\/upload-limits'\)/)
  assert.match(detailSource, /limits\.reviewReady === true && limits\.submissionMode === 'ai-review'/)
  assert.match(detailSource, /这是待专业配置草稿，尚未执行 AI 审核/)
  assert.match(detailSource, /当前没有评分、专业意见、立项报告或人工复核结论/)
  assert.match(detailSource, /configurationPending \? '待 AI 审核' : \(manualReview\.manualReviewStatus/)
  assert.match(detailSource, /configurationPending \? '待 AI 审核 \/ 未开放 \/ 未开放'/)
  assert.match(detailSource, /configurationPending \? '未开放' : \(signOffRecord\.status/)
  assert.match(detailSource, /configurationPending \? '未开放' : \(archiveRecord\.status/)
  assert.match(detailSource, /disabled=\{previewingReport \|\| configurationPending\}/)
  assert.match(detailSource, /disabled=\{savingManualReview \|\| !canReview \|\| configurationPending\}/)
  assert.match(detailSource, /disabled=\{savingSignOff \|\| configurationPending/)
  assert.match(detailSource, /尚未生成专业审核意见；当前草稿不会伪造评分或审核结论/)
  assert.match(detailSource, /暂无最终汇总意见。该方案当前仅保存原始标题和附件/)
})

test('催办草稿不得冒充已发送催办', () => {
  assert.match(reviewSource, /系统草稿（未发送）/)
  assert.match(reviewSource, /此操作不会发送企业微信、邮件或电话通知/)
  assert.match(rulesSource, /系统只生成未发送草稿/)
  assert.match(homeSource, /未发送草稿不计完成/)
  assert.match(reviewSource, /已生成未发送草稿 \{bulkReminderResult\.created \|\| 0\} 个/)
})

test('改密通知文案必须明示未发送，不得冒充通知送达', () => {
  assert.match(usersSource, /账号改密通知文案（未发送）/)
  assert.match(homeSource, /最近改密通知文案（未发送）/)
  assert.match(statsSource, /状态：未发送/)
  assert.match(logsSource, /发送数：\$\{info\.sentCount\} 个；交付状态/)
  assert.match(settingsSource, /涉及 .* 个账号，未发送/)
  assert.doesNotMatch(usersSource, /可继续通知需改密账号/)
})

test('兜底链路不得生成标题哈希分或固定关键词分', () => {
  assert.doesNotMatch(backendSource, /function scoreFor\(/)
  assert.doesNotMatch(backendSource, /charCodeAt\(0\)/)
  assert.doesNotMatch(hermesSource, /score:\s*profileHit\s*\?\s*72\s*:\s*66/)
  assert.doesNotMatch(hermesSource, /score:\s*profileHit\s*\?\s*91\s*:\s*86/)
})

test('首次初始化不写入业务规则、知识模板或虚构人工日志', () => {
  assert.match(backendSource, /function defaultRules\(\)\s*\{[^}]*return \[\]\s*\}/)
  assert.match(backendSource, /function defaultKnowledgeEntries\(\)\s*\{[^}]*return \[\]\s*\}/)
  assert.doesNotMatch(backendSource, /完成市场拓展立项报告模板配置/)
})

test('浏览器 CSV 导出阻断表格公式注入并保留正常文本', () => {
  for (const value of ['=HYPERLINK("https://example.invalid")', '+cmd', '-1+2', '@SUM(A1:A2)', '  =1+1', '\t=1+1']) {
    assert.match(spreadsheetSafeText(value), /^'/)
    assert.match(csvCell(value), /^"'/)
  }
  assert.equal(spreadsheetSafeText('正常方案'), '正常方案')
  assert.equal(csvCell('带"引号'), '"带""引号"')
  for (const source of [submitSource, reviewSource, usersSource, logsSource, settingsSource]) {
    assert.match(source, /import \{ csvCell \} from '\.\.\/lib\/csv'/)
  }
})

test('Hermes 自动状态刷新保持只读，仅人工检查使用 POST 留痕', () => {
  assert.match(botsSource, /audit\s*\?\s*await api\.post\('\/profiles\/hermes-status', \{\}\)\s*:\s*await api\.get\('\/profiles\/hermes-status'\)/)
  assert.match(botsSource, /onClick=\{\(\) => loadHermesStatus\(\{ audit: true \}\)\}/)
  assert.match(settingsSource, /const data = await api\.post\('\/profiles\/hermes-status', \{\}\)/)
  assert.match(settingsSource, /refreshLaunchReadiness[\s\S]*?api\.get\('\/profiles\/hermes-status'\)/)
})

test('角色权限矩阵只允许在后端安全上限内减配或恢复', () => {
  assert.match(settingsSource, /const roleCeiling = defaultRolePermissions\[role\] \|\| \[\]/)
  assert.match(settingsSource, /if \(role === '管理员'\) return setError\('管理员固定保留全部权限，不允许增减'\)/)
  assert.match(settingsSource, /if \(!roleCeiling\.includes\(permissionKey\)\) return setError\('该权限超出角色安全上限，不允许启用'\)/)
  assert.match(settingsSource, /const withinRoleCeiling = \(defaultRolePermissions\[role\] \|\| \[\]\)\.includes\(permission\.key\)/)
  assert.match(settingsSource, /const lockedReason = !withinRoleCeiling/)
  assert.match(settingsSource, /超出角色安全上限，不可启用/)
  assert.match(settingsSource, /安全上限外/)
  assert.match(settingsSource, /遗留使用者固定提交权限，不在此处分配/)
  assert.match(settingsSource, /超出角色安全上限的权限不可启用；非管理员全表只读/)
})

test('生产运行项只读展示，不再提供必然失败或不会生效的假配置', () => {
  assert.match(settingsSource, /生产审核引擎固定使用云端受控的本机 Hermes Gateway/)
  assert.match(settingsSource, /Provider、模型、Base URL 与网关认证变量由部署管理/)
  assert.match(settingsSource, /const managedAiProvider = aiRuntime\.provider/)
  assert.match(settingsSource, /const managedAiBaseUrl = aiRuntime\.baseUrl/)
  assert.match(settingsSource, /const managedFrontendUrl = managedPublicDomain/)
  assert.match(settingsSource, /const managedBackendPort = runtime\?\.port/)
  assert.match(settingsSource, /const managedApiPrefix = '\/api'/)
  assert.doesNotMatch(settingsSource, /<option value="(?:local|openai|custom)"/)
  for (const key of ['aiProvider', 'aiModel', 'aiBaseUrl', 'aiApiKeyEnv', 'frontendUrl', 'backendPort', 'apiPrefix']) {
    assert.doesNotMatch(settingsSource, new RegExp(`updateSystemConfig\\('${key}'`))
  }
  assert.match(settingsSource, /AI 与服务运行项由云端部署管理，不会在此修改/)
  assert.match(settingsSource, /公网通过 \/review-api\/ 代理/)
  assert.match(settingsSource, /const ignoredManagedFields = Array\.isArray\(data\.ignoredManagedFields\)/)
  assert.match(settingsSource, /云端固定项保持运行态值/)
  assert.match(settingsSource, /可编辑的账号安全与诊断配置已保存；云端固定运行项未变更/)
  assert.match(settingsSource, /const aiInferenceState = aiRuntime\.agentConfigured === true/)
  assert.match(settingsSource, /外部推理已安全停用，等待供应商密钥轮换/)
  assert.match(settingsSource, /未完成前系统保持 draft-only/)
  assert.match(settingsSource, /已安全停用 · draft-only/)
  assert.doesNotMatch(settingsSource, /aiRuntime\.provider === 'hermes' \? '通过'/)
})

test('系统备份只接受带清单和逐附件指纹的流式归档', () => {
  assert.match(settingsSource, /\.firstcare-review-backup\.tgz/)
  assert.match(settingsSource, /uploadFormatError\(file, \['\.tgz'\], '备份归档'\)/)
  assert.match(settingsSource, /application\/gzip,application\/x-gzip,\.tgz,\.firstcare-review-backup\.tgz/)
  assert.match(settingsSource, /校验 manifest、store 与每个附件的大小和 SHA256/)
  assert.doesNotMatch(settingsSource, /仅支持系统导出的备份 JSON/)
})

test('大体量备份通过同源单次票据交给浏览器原生流式下载', () => {
  assert.match(settingsSource, /api\.post\('\/system-backup\/export-ticket'\)/)
  assert.match(settingsSource, /api\.post\(`\/system-backup\/snapshots\/\$\{encodeURIComponent\(name\)\}\/download-ticket`\)/)
  assert.match(settingsSource, /downloadWithOneTimeTicket\(ticket\)/)
  assert.doesNotMatch(settingsSource, /downloadFile\('\/system-backup\/export'/)
  assert.doesNotMatch(settingsSource, /downloadFile\(`\/system-backup\/snapshots/)
  assert.match(apiSource, /expectedPrefix = '\/review-api\/system-backup\/download\/'/)
  assert.match(apiSource, /url\.origin !== window\.location\.origin/)
  assert.match(apiSource, /\^\[A-Za-z0-9_-\]\{43\}\$/)
  assert.match(apiSource, /ticket\.oneTime !== true/)
  assert.match(apiSource, /link\.referrerPolicy = 'no-referrer'/)
  assert.match(apiSource, /link\.click\(\)/)
})
