import{Router}from'express';import db from'../db.js';import{requireAdmin}from'../auth.js';import{logOperation}from'../audit.js';import{projectDataBlockedPayload,readProjectDataGate}from'../data-quality-gate.js';import{evaluateMeetingDiscipline}from'../weekly-meeting.js';import{evaluateFormalMonthlyGate}from'../formal-output-quality.js';import{spawnSync}from'node:child_process';import fs from'node:fs';import path from'node:path';import os from'node:os';import crypto from'node:crypto';
const router=Router(),outRoot=process.env.FORMAL_OUTPUT_DIR||path.resolve(process.cwd(),'generated-reports');

const actor=(req:any)=>String(req.user?.username||req.user?.name||'system');
const clean=(s:string)=>s.replace(/[\\/:*?"<>|]/g,'_').slice(0,100);
const sha=(p:string)=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function areaSql(area:string,withWhere=false){return area==='华北'||area==='全部'?{clause:'',params:[]as any[]}:{clause:`${withWhere?' WHERE':' AND'} area=?`,params:[area]}}
function monthlyGate(area:string,period:string){
  const filter=areaSql(area)
  const expected=Number((db.prepare(`SELECT COUNT(*) n FROM projects WHERE validation_status='verified' AND active_status='active'${filter.clause.replace(' WHERE',' AND')}`).get(...filter.params)as any)?.n||0)
  const snap=db.prepare(`SELECT COUNT(*) n,SUM(CASE WHEN COALESCE(quality_status,'unverified')!='verified' OR COALESCE(TRIM(source),'')='' OR LOWER(source) IN ('regression','demo','manual','seed') THEN 1 ELSE 0 END) invalid FROM project_monthly_snapshots WHERE month=?${filter.clause.replace(' WHERE',' AND')}`).get(period,...filter.params)as any
  const run=db.prepare('SELECT status FROM snapshot_runs WHERE month=? ORDER BY id DESC LIMIT 1').get(period)as any
  const forecast=db.prepare(`SELECT COUNT(*) n,SUM(CASE WHEN workflow_status='locked' THEN 0 ELSE 1 END) unlocked FROM project_forecasts WHERE month=?${filter.clause.replace(' WHERE',' AND')}`).get(period,...filter.params)as any
  return evaluateFormalMonthlyGate({period,expectedProjectCount:expected,snapshotCount:Number(snap?.n||0),invalidSnapshotCount:Number(snap?.invalid||0),snapshotRunStatus:run?.status||null,forecastCount:Number(forecast?.n||0),unlockedForecastCount:Number(forecast?.unlocked||0)})
}
function monthly(area:string,period:string){
  const filter=areaSql(area),args=[period,...filter.params]
  const s=db.prepare(`SELECT COUNT(*) projects,SUM(ytd_income) income,SUM(ytd_cost) cost,SUM(receivable) receivable,SUM(received) received,ROUND(AVG(quality_score),1) quality,ROUND(AVG(customer_satisfaction),1) satisfaction,SUM(safety_incidents) incidents,SUM(complaint_count) complaints FROM project_monthly_snapshots WHERE month=? AND quality_status='verified'${filter.clause}`).get(...args)as any
  const projects=db.prepare(`SELECT project_name name,area,ytd_income,ytd_cost,receivable,received,complaint_count,safety_incidents,source FROM project_monthly_snapshots WHERE month=? AND quality_status='verified'${filter.clause} ORDER BY area,project_name`).all(...args)as any[]
  const forecasts=db.prepare(`SELECT workflow_status,COUNT(*) n FROM project_forecasts WHERE month=?${filter.clause} GROUP BY workflow_status`).all(...args)as any[]
  const run=db.prepare('SELECT month,status,message,created_at FROM snapshot_runs WHERE month=? ORDER BY id DESC LIMIT 1').get(period)as any
  const num=(v:any,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d)
  const cr=s?.receivable>0?Number(s.received)/Number(s.receivable)*100:null,pr=s?.income>0?(Number(s.income)-Number(s.cost))/Number(s.income)*100:null
  const risk=projects.map(p=>({...p,cr:p.receivable>0?100*p.received/p.receivable:null,pr:p.ytd_income>0?100*(p.ytd_income-p.ytd_cost)/p.ytd_income:null})).sort((a,b)=>(a.cr??Infinity)-(b.cr??Infinity)).slice(0,8)
  const wf=Object.fromEntries(forecasts.map(x=>[x.workflow_status,x.n]))
  return{title:`第一服务华北地区${period}经营月报`,subtitle:`范围：${area}｜数据快照：${period}`,period,area,sections:[['经营总览',[`纳入项目：${s.projects||0}个`,`累计收入：${num(s.income)}万元；累计成本：${num(s.cost)}万元`,`综合利润率：${num(pr)}%；综合收费率：${num(cr)}%`,`品质评分：${num(s.quality)}；满意度：${num(s.satisfaction)}；安全事故：${num(s.incidents,0)}；投诉：${num(s.complaints,0)}`]],['滚动预测审批',[`锁定${wf.locked||0}项；其他状态${Object.entries(wf).filter(([k])=>k!=='locked').reduce((n,[,v])=>n+Number(v),0)}项`]],['重点风险项目',risk.map(x=>`${x.area}/${x.name}：收费率${num(x.cr)}%，利润率${num(x.pr)}%，投诉${num(x.complaint_count,0)}，安全${num(x.safety_incidents,0)}`)],['数据质量',[`期间快照：${run?.month||'—'}；状态：${run?.status||'—'}`,`快照来源：${[...new Set(projects.map(p=>p.source||'—'))].join('、')}`]]],evidence:{projectCount:s.projects||0,period,snapshotRunStatus:run?.status||null,forecastStatuses:wf,source:'project_monthly_snapshots'}}
}
function weekly(id:number){const m=db.prepare('SELECT * FROM weekly_meetings WHERE id=?').get(id)as any;if(!m)throw new Error('周会不存在');const items=db.prepare("SELECT id,meeting_id,project_id,project_name,risk_type,issue,decision,owner,due_date,status,created_at,updated_at FROM weekly_meeting_items WHERE meeting_id=? AND source_type NOT LIKE 'task-%' ORDER BY id").all(id)as any[],discipline=evaluateMeetingDiscipline(items);if(m.status!=='closed'||!discipline.compliant)throw new Error(`周会会议决策不完整：状态${m.status}，完成${discipline.complete}/${discipline.total}，不能生成正式纪要`);const decided=items.filter(x=>x.decision);return{title:`${m.title}纪要`,subtitle:`会议周：${m.week_start}｜状态：${m.status}`,period:m.week_start,area:m.area,sections:[['会议概况',[`会议范围：${m.area}`,`会议状态：${m.status}`,`议题${items.length}项；形成决策${decided.length}项`,m.summary||'未填写会议总结']],['议题与决策',items.map((x,i)=>`${i+1}. ${x.project_name||'经营管理'}｜${x.issue}｜决策：${x.decision||'未形成'}｜责任人：${x.owner||'未指定'}｜计划日期：${x.due_date||'未填写'}`)],['会后记录',['会议决策作为经营记录归档','责任人与计划日期仅用于纪要完整性','系统仅保存会议纪要，不发起后续流程']]],evidence:{meetingId:m.id,itemCount:items.length,decisionCount:decided.length,status:m.status}}}
router.get('/api/formal-outputs',requireAdmin,(req,res)=>{const rows=(db.prepare('SELECT * FROM formal_output_archives ORDER BY id DESC LIMIT 100').all()as any[]).map(x=>({...x,files:JSON.parse(x.files_json),evidence:JSON.parse(x.evidence_json)}));res.json({rows})});
router.post('/api/formal-outputs/generate',requireAdmin,(req,res)=>{try{if(!readProjectDataGate(db).ready)return res.status(409).json(projectDataBlockedPayload(db));const type=String(req.body?.type||''),area=String(req.body?.area||'华北'),period=String(req.body?.period||new Date().toISOString().slice(0,7));if(!['monthly','weekly'].includes(type))return res.status(400).json({error:'type仅支持monthly或weekly'});if(type==='monthly'){const gate=monthlyGate(area,period);if(!gate.ready)return res.status(409).json({error:'指定期间尚未通过正式输出门禁',code:'FORMAL_MONTHLY_QUALITY_BLOCKED',dataQuality:gate})}const d:any=type==='monthly'?monthly(area,period):weekly(Number(req.body?.meeting_id));const stamp=new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14),base=clean(`${d.title}_${stamp}`),dir=path.join(outRoot,`${type}-${stamp}-${crypto.randomBytes(3).toString('hex')}`);fs.mkdirSync(dir,{recursive:true});const input=path.join(os.tmpdir(),`formal-${process.pid}-${Date.now()}.json`);fs.writeFileSync(input,JSON.stringify({type,title:d.title,subtitle:d.subtitle,base_name:base,sections:d.sections}));const script=path.resolve(process.cwd(),'scripts/generate_formal_outputs.py'),python=process.env.FORMAL_OUTPUT_PYTHON||'/usr/bin/python3',run=spawnSync(python,[script,'--input',input,'--outdir',dir],{encoding:'utf8',timeout:120000});fs.rmSync(input,{force:true});if(run.status!==0)throw new Error(`文档生成失败：${(run.stderr||run.stdout).slice(0,4000)}`);const files:any={};for(const ext of['md','docx','pptx']){const p=path.join(dir,`${base}.${ext}`);if(!fs.existsSync(p)||fs.statSync(p).size<100)throw new Error(`${ext}文件生成失败`);files[ext]={path:p,size:fs.statSync(p).size,sha256:sha(p)}}const createdAt=new Date().toISOString(),r=db.prepare('INSERT INTO formal_output_archives(output_type,period,area,title,base_name,files_json,evidence_json,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(type,d.period||period,d.area||area,d.title,base,JSON.stringify(files),JSON.stringify(d.evidence),actor(req),createdAt);logOperation(req,type==='monthly'?'生成正式月报三件套':'生成正式周会纪要三件套',`formal_output:${r.lastInsertRowid}`,{period:d.period||period,area:d.area||area,formats:Object.keys(files),evidence:d.evidence});res.status(201).json({id:Number(r.lastInsertRowid),type,title:d.title,files,evidence:d.evidence,created_at:createdAt})}catch(e:any){res.status(409).json({error:e.message})}});
router.get('/api/formal-outputs/:id/download/:format',requireAdmin,(req,res)=>{const row=db.prepare('SELECT * FROM formal_output_archives WHERE id=?').get(req.params.id)as any;if(!row)return res.status(404).json({error:'归档不存在'});const format=String(req.params.format),files=JSON.parse(row.files_json),f=files[format];if(!f||!['md','docx','pptx'].includes(format))return res.status(404).json({error:'格式不存在'});const resolved=path.resolve(f.path);if(!resolved.startsWith(path.resolve(outRoot)+path.sep)||!fs.existsSync(resolved))return res.status(404).json({error:'归档文件不存在'});logOperation(req,'下载正式经营输出',`formal_output:${row.id}`,{format,period:row.period});res.download(resolved,`${row.base_name}.${format}`)});
export default router;
