#!/usr/bin/env python3
import argparse,json,os,zipfile,html
from pathlib import Path
from datetime import datetime

def esc(s): return html.escape(str(s or ''))
def money(v): return f"{float(v or 0):,.1f}"
def pptx_text_slide(title, lines, index):
    shapes=[]; y=950000
    for i,line in enumerate(lines[:9],2):
        text=esc(line); shapes.append(f'''<p:sp><p:nvSpPr><p:cNvPr id="{i}" name="文本 {i}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="700000" y="{y}"/><a:ext cx="10800000" cy="500000"/></a:xfrm><a:prstGeom prst="roundRect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="0B1B2B"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr lIns="120000" rIns="120000" tIns="60000" bIns="60000"/><a:lstStyle/><a:p><a:r><a:rPr lang="zh-CN" sz="1500"><a:solidFill><a:srgbClr val="DCEAF5"/></a:solidFill><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/></a:rPr><a:t>{text}</a:t></a:r><a:endParaRPr lang="zh-CN"/></a:p></p:txBody></p:sp>''');y+=800000 if index==1 else 580000
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="050E1A"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="20" name="标题"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="700000" y="280000"/><a:ext cx="10800000" cy="520000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="zh-CN" sz="2600" b="1"><a:solidFill><a:srgbClr val="00CCF9"/></a:solidFill><a:ea typeface="Microsoft YaHei"/></a:rPr><a:t>{esc(title)}</a:t></a:r></a:p></p:txBody></p:sp>{''.join(shapes)}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>'''
def create_pptx(path, slides):
    n=len(slides);ct='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>'''+''.join(f'<Override PartName="/ppt/slides/slide{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>' for i in range(1,n+1))+'''</Types>'''
    pres='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>'''+''.join(f'<p:sldId id="{255+i}" r:id="rId{i+1}"/>' for i in range(1,n+1))+'''</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>'''
    prels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>'''+''.join(f'<Relationship Id="rId{i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{i}.xml"/>' for i in range(1,n+1))+'''</Relationships>'''
    rootrels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>'''
    layout='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank"><p:cSld name="空白"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>'''
    master='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>'''
    theme='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="华北经营"><a:themeElements><a:clrScheme name="深蓝"><a:dk1><a:srgbClr val="050E1A"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="0B1B2B"/></a:dk2><a:lt2><a:srgbClr val="DCEAF5"/></a:lt2><a:accent1><a:srgbClr val="00CCF9"/></a:accent1><a:accent2><a:srgbClr val="2DD4BF"/></a:accent2><a:accent3><a:srgbClr val="FACC15"/></a:accent3><a:accent4><a:srgbClr val="FB7185"/></a:accent4><a:accent5><a:srgbClr val="60A5FA"/></a:accent5><a:accent6><a:srgbClr val="A78BFA"/></a:accent6><a:hlink><a:srgbClr val="00CCF9"/></a:hlink><a:folHlink><a:srgbClr val="A78BFA"/></a:folHlink></a:clrScheme><a:fontScheme name="微软雅黑"><a:majorFont><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:minorFont></a:fontScheme><a:fmtScheme name="默认"><a:fillStyleLst/><a:lnStyleLst/><a:effectStyleLst/><a:bgFillStyleLst/></a:fmtScheme></a:themeElements></a:theme>'''
    with zipfile.ZipFile(path,'w',zipfile.ZIP_DEFLATED) as z:
        for name,data in {'[Content_Types].xml':ct,'_rels/.rels':rootrels,'ppt/presentation.xml':pres,'ppt/_rels/presentation.xml.rels':prels,'ppt/slideLayouts/slideLayout1.xml':layout,'ppt/slideMasters/slideMaster1.xml':master,'ppt/theme/theme1.xml':theme,'ppt/slideMasters/_rels/slideMaster1.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>'}.items():z.writestr(name,data)
        for i,(title,lines) in enumerate(slides,1):z.writestr(f'ppt/slides/slide{i}.xml',pptx_text_slide(title,lines,i));z.writestr(f'ppt/slides/_rels/slide{i}.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>')
def create_docx(path,title,sections):
    from docx import Document
    from docx.shared import Pt,RGBColor
    from docx.oxml.ns import qn
    d=Document();d.core_properties.title=title;p=d.add_heading(title,0);p.runs[0].font.color.rgb=RGBColor(5,46,79)
    for heading,lines in sections:
        d.add_heading(heading,1)
        for line in lines:d.add_paragraph(str(line),style='List Bullet' if len(lines)>1 else None)
    for para in d.paragraphs:
        for run in para.runs:run.font.name='Microsoft YaHei';run._element.rPr.rFonts.set(qn('w:eastAsia'),'Microsoft YaHei');run.font.size=run.font.size or Pt(11)
    d.save(path)
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--input',required=True);ap.add_argument('--outdir',required=True);args=ap.parse_args();data=json.load(open(args.input));out=Path(args.outdir);out.mkdir(parents=True,exist_ok=True);kind=data['type'];base=data['base_name'];title=data['title'];sections=data['sections'];
    md='# '+title+'\n\n'+'\n\n'.join('## '+h+'\n\n'+'\n'.join('- '+str(x) for x in lines) for h,lines in sections)+'\n';(out/(base+'.md')).write_text(md)
    create_docx(out/(base+'.docx'),title,sections)
    cover=[data.get('subtitle',''),f"生成时间：{datetime.now():%Y-%m-%d %H:%M}",'真实数据｜经营结论均来自驾驶舱当前数据库','管理闭环｜风险、责任人、任务和复核同源','版本留痕｜每次生成独立归档并记录SHA-256','第一服务华北地区 · 经营复盘 · 任务督办 · 滚动预测'];slides=[(title,cover)] + [(h,lines) for h,lines in sections[:7]];create_pptx(out/(base+'.pptx'),slides)
    result={'files':{ext:str(out/(base+'.'+ext)) for ext in ['md','docx','pptx']},'slides':len(slides),'sections':len(sections)};print(json.dumps(result,ensure_ascii=False))
if __name__=='__main__':main()
